import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import NavLayout from './ui/NavLayout';
import { HamburgerContextProvider } from './ui/HamburgerContext';
import { WindowContextProvider } from './ui/WindowContext';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' crossOrigin='' />
        <link
          href='https://fonts.googleapis.com/css2?family=Actor&family=Amaranth:ital,wght@0,400;0,700;1,400;1,700&display=swap'
          rel='stylesheet'
        />
      </head>

      <body className='bg-[#1F1529] h-full w-full flex-col flex relative'>
        <WindowContextProvider>
          <HamburgerContextProvider>
            <NavLayout>{children}</NavLayout>
          </HamburgerContextProvider>
        </WindowContextProvider>
      </body>
    </html>
  );
}
